# Generated by Django 4.0.1 on 2022-02-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_userinfo_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='money_amount',
            field=models.IntegerField(default=0),
        ),
    ]
