# Generated by Django 4.0.1 on 2022-02-21 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Room', '0004_crypto_chart_crypto_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='description',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='indicator_chart_ma',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='indicator_chart_macd',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='indicator_chart_rsi',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='indicator_chart_stockhastic',
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(null=True)),
                ('order_amount', models.IntegerField(null=True)),
                ('order_type', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=50, null=True)),
                ('order_size', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('indicator_chart_ma', models.ImageField(null=True, upload_to='')),
                ('indicator_chart_macd', models.ImageField(null=True, upload_to='')),
                ('indicator_chart_rsi', models.ImageField(null=True, upload_to='')),
                ('indicator_chart_stockhastic', models.ImageField(null=True, upload_to='')),
                ('crpyto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.crypto')),
            ],
        ),
    ]
