# Generated by Django 4.0.1 on 2022-02-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0006_alter_crypto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Indicators',
        ),
    ]
