# Generated by Django 4.0.1 on 2022-02-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0007_crypto_description_delete_indicators'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='type',
            field=models.CharField(choices=[('BTC-USDT', 'BTC-USDT'), ('ETH-USDT', 'ETH-USDT')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
