# Generated by Django 4.0.1 on 2022-02-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0008_crypto_type_alter_crypto_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='chart',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
