# Generated by Django 4.0.1 on 2022-02-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0009_alter_crypto_chart_alter_crypto_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='type',
            new_name='crypto_type',
        ),
    ]
