# Generated by Django 4.0.1 on 2022-02-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0010_rename_type_crypto_crypto_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='crypto_type',
            field=models.CharField(choices=[('BTC-USD', 'BTC-USD'), ('ETH-USD', 'ETH-USD')], max_length=50, null=True),
        ),
    ]
