# Generated by Django 4.0.1 on 2022-04-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0013_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crypto',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='price',
        ),
    ]
